version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec bin/dev -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "8080:3000"
    tty: true
    depends_on:
      - db